# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Love
email: chardane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about coding life, and love. Tutorials, tuts and
  random things that I've learned in my love affair with code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "chardane.github.io" # the base hostname & protocol for your site
twitter_username: chardane
github_username:  chardane
permalink: /codelove/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM
